apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: cockroach-operator
  name: cockroach-operator-webhook-service
  namespace: ${operator_namespace}
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    app: cockroach-operator