apiVersion: v1
kind: Service
metadata:
  name: cockroach-nlb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    external-dns.alpha.kubernetes.io/hostname: "${dnsname}"
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "${additional_tags}"

spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: sql
    port: 26257
    protocol: TCP
    targetPort: 26257
  selector:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: ${crdb_cluster}
    app.kubernetes.io/name: cockroachdb
  type: LoadBalancer